version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  php:
    build:
      context: ./php-fpm
    volumes:
      - ../:/usr/local/app
    links:
      - db

  web:
    build:
      context: ./apache
    ports:
      - "8000:80"
    volumes:
      - ../:/usr/local/apache2/htdocs/
    links:
      - php
